insert into songs (Title, Artist, Genre) values ('Sunset Symphony', 'John Johnson', 'rock');
insert into songs (Title, Artist, Genre) values ('Soothing Symphony', 'William Thomas', 'jazz');
insert into songs (Title, Artist, Genre) values ('Echoes of Enchantment', 'Lily Turner', 'metal');
insert into songs (Title, Artist, Genre) values ('Lavender Lullaby', 'William Thomas', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Ethereal Echoes', 'Grace Hill', 'jazz');
insert into songs (Title, Artist, Genre) values ('Whispering Whispers', 'Amelia Scott', 'classical');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Chloe Baker', 'metal');
insert into songs (Title, Artist, Genre) values ('Harmonious Hues', 'Sophia Anderson', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Majestic Melodies', 'Ava Garcia', 'classical');
insert into songs (Title, Artist, Genre) values ('Symphony Sands', 'Andrew Cook', 'indie');
insert into songs (Title, Artist, Genre) values ('Opal Overture', 'Olivia Martinez', 'metal');
insert into songs (Title, Artist, Genre) values ('Amber Allegro', 'Lily Turner', 'electronic');
insert into songs (Title, Artist, Genre) values ('Tranquil Tunes', 'Amelia Scott', 'reggae');
insert into songs (Title, Artist, Genre) values ('Twilight Tranquility', 'William Thomas', 'jazz');
insert into songs (Title, Artist, Genre) values ('Mystical Melodies', 'Christopher Young', 'metal');
insert into songs (Title, Artist, Genre) values ('Whirlwind Waltz', 'Chloe Baker', 'jazz');
insert into songs (Title, Artist, Genre) values ('Lavender Lullaby', 'Matthew Hernandez', 'electronic');
insert into songs (Title, Artist, Genre) values ('Melody of the Moon', 'Daniel Taylor', 'reggae');
insert into songs (Title, Artist, Genre) values ('Majestic Melodies', 'William Thomas', 'indie');
insert into songs (Title, Artist, Genre) values ('Lavender Lullaby', 'Samantha Lee', 'indie');
insert into songs (Title, Artist, Genre) values ('Midnight Serenade', 'Christopher Young', 'classical');
insert into songs (Title, Artist, Genre) values ('Harmony Haven', 'Isabella Lopez', 'metal');
insert into songs (Title, Artist, Genre) values ('Echoes of Enchantment', 'Amelia Scott', 'rock');
insert into songs (Title, Artist, Genre) values ('Enchanted Euphoria', 'Andrew Cook', 'rock');
insert into songs (Title, Artist, Genre) values ('Whispering Whispers', 'Samantha Lee', 'pop');
insert into songs (Title, Artist, Genre) values ('Emerald Euphony', 'Charlotte Lewis', 'jazz');
insert into songs (Title, Artist, Genre) values ('Twilight Tranquility', 'Lily Turner', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Electric Dreams', 'Ethan Gonzalez', 'metal');
insert into songs (Title, Artist, Genre) values ('Sunset Symphony', 'Sophia Anderson', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Moonlit Minuet', 'Grace Hill', 'country');
insert into songs (Title, Artist, Genre) values ('Violet Vibration', 'Samantha Lee', 'jazz');
insert into songs (Title, Artist, Genre) values ('Moonlit Minuet', 'Alexander Adams', 'electronic');
insert into songs (Title, Artist, Genre) values ('Whispering Winds', 'Mia Rodriguez', 'classical');
insert into songs (Title, Artist, Genre) values ('Opal Ode', 'David Wilson', 'classical');
insert into songs (Title, Artist, Genre) values ('Moonlit Minuet', 'Emily Davis', 'reggae');
insert into songs (Title, Artist, Genre) values ('Crimson Crescendo', 'Ava Garcia', 'country');
insert into songs (Title, Artist, Genre) values ('Amber Allegro', 'Alice Smith', 'classical');
insert into songs (Title, Artist, Genre) values ('Tranquil Tunes', 'Benjamin Murphy', 'reggae');
insert into songs (Title, Artist, Genre) values ('Melodic Mirage', 'Olivia Martinez', 'jazz');
insert into songs (Title, Artist, Genre) values ('Ethereal Echoes', 'James Perez', 'classical');
insert into songs (Title, Artist, Genre) values ('Symphony of the Stars', 'John Johnson', 'indie');
insert into songs (Title, Artist, Genre) values ('Radiant Rhapsody', 'Daniel Taylor', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Whispering Whispers', 'Alice Smith', 'country');
insert into songs (Title, Artist, Genre) values ('Firefly Waltz', 'Christopher Young', 'classical');
insert into songs (Title, Artist, Genre) values ('Sapphire Symphony', 'Chloe Baker', 'reggae');
insert into songs (Title, Artist, Genre) values ('Amber Allegro', 'Christopher Young', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Celestial Cadence', 'Benjamin Murphy', 'rock');
insert into songs (Title, Artist, Genre) values ('Radiant Rhapsody', 'William Thomas', 'reggae');
insert into songs (Title, Artist, Genre) values ('Symphony Sands', 'Grace Hill', 'jazz');
insert into songs (Title, Artist, Genre) values ('Enchanted Euphoria', 'Ethan Gonzalez', 'jazz');
insert into songs (Title, Artist, Genre) values ('Twilight Temptation', 'Alice Smith', 'electronic');
insert into songs (Title, Artist, Genre) values ('Ethereal Echoes', 'Isabella Lopez', 'pop');
insert into songs (Title, Artist, Genre) values ('Echoes of Eternity', 'David Wilson', 'country');
insert into songs (Title, Artist, Genre) values ('Whispering Whispers', 'Daniel Taylor', 'metal');
insert into songs (Title, Artist, Genre) values ('Twilight Temptation', 'Amelia Scott', 'classical');
insert into songs (Title, Artist, Genre) values ('Ruby Rhapsody', 'Christopher Young', 'rock');
insert into songs (Title, Artist, Genre) values ('Whispers in the Wind', 'John Johnson', 'pop');
insert into songs (Title, Artist, Genre) values ('Twilight Temptation', 'James Perez', 'country');
insert into songs (Title, Artist, Genre) values ('Amber Aria', 'Amelia Scott', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Majestic Melancholy', 'Samantha Lee', 'rock');
insert into songs (Title, Artist, Genre) values ('Melody of the Moon', 'Lily Turner', 'indie');
insert into songs (Title, Artist, Genre) values ('Luminous Lullaby', 'Isabella Lopez', 'pop');
insert into songs (Title, Artist, Genre) values ('Echoes of Eden', 'Grace Hill', 'pop');
insert into songs (Title, Artist, Genre) values ('Sunset Symphony', 'Alice Smith', 'pop');
insert into songs (Title, Artist, Genre) values ('Echoes of Eternity', 'Isabella Lopez', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Majestic Melancholy', 'Andrew Cook', 'reggae');
insert into songs (Title, Artist, Genre) values ('Tranquil Tunes', 'Amelia Scott', 'rock');
insert into songs (Title, Artist, Genre) values ('Enchanted Elegy', 'Lily Turner', 'metal');
insert into songs (Title, Artist, Genre) values ('Firefly Waltz', 'James Perez', 'jazz');
insert into songs (Title, Artist, Genre) values ('Crimson Cadence', 'Grace Hill', 'electronic');
insert into songs (Title, Artist, Genre) values ('Dreamy Divinity', 'Ethan Gonzalez', 'metal');
insert into songs (Title, Artist, Genre) values ('Opal Ode', 'Lily Turner', 'jazz');
insert into songs (Title, Artist, Genre) values ('Whispers of the Wind', 'James Perez', 'pop');
insert into songs (Title, Artist, Genre) values ('Luminous Lullaby', 'Alice Smith', 'pop');
insert into songs (Title, Artist, Genre) values ('Whispering Winds', 'Chloe Baker', 'jazz');
insert into songs (Title, Artist, Genre) values ('Serenity''s Song', 'Andrew Cook', 'rock');
insert into songs (Title, Artist, Genre) values ('Whispering Whispers', 'Emily Davis', 'metal');
insert into songs (Title, Artist, Genre) values ('Soothing Symphony', 'Andrew Cook', 'country');
insert into songs (Title, Artist, Genre) values ('Amber Allegro', 'Alexander Adams', 'country');
insert into songs (Title, Artist, Genre) values ('Lavender Lament', 'Lily Turner', 'pop');
insert into songs (Title, Artist, Genre) values ('Echoing Embrace', 'Michael Brown', 'rock');
insert into songs (Title, Artist, Genre) values ('Harmonious Hues', 'Ethan Gonzalez', 'indie');
insert into songs (Title, Artist, Genre) values ('Enchanted Euphoria', 'William Thomas', 'indie');
insert into songs (Title, Artist, Genre) values ('Melody of the Moon', 'Lily Turner', 'electronic');
insert into songs (Title, Artist, Genre) values ('Majestic Melodies', 'Michael Brown', 'reggae');
insert into songs (Title, Artist, Genre) values ('Lavender Lament', 'William Thomas', 'classical');
insert into songs (Title, Artist, Genre) values ('Whispering Whispers', 'William Thomas', 'jazz');
insert into songs (Title, Artist, Genre) values ('Twilight Temptation', 'Christopher Young', 'reggae');
insert into songs (Title, Artist, Genre) values ('Celestial Chorus', 'Benjamin Murphy', 'metal');
insert into songs (Title, Artist, Genre) values ('Symphony of the Stars', 'Christopher Young', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Starry Sonata', 'Charlotte Lewis', 'pop');
insert into songs (Title, Artist, Genre) values ('Lavender Lament', 'Emily Davis', 'metal');
insert into songs (Title, Artist, Genre) values ('Melody of the Moon', 'Alexander Adams', 'classical');
insert into songs (Title, Artist, Genre) values ('Echoes of Enchantment', 'Olivia Martinez', 'indie');
insert into songs (Title, Artist, Genre) values ('Whispering Whispers', 'William Thomas', 'pop');
insert into songs (Title, Artist, Genre) values ('Echoes of Eternity', 'Daniel Taylor', 'pop');
insert into songs (Title, Artist, Genre) values ('Lavender Lament', 'Andrew Cook', 'indie');
insert into songs (Title, Artist, Genre) values ('Emerald Elegy', 'Michael Brown', 'country');
insert into songs (Title, Artist, Genre) values ('Opal Ode', 'Christopher Young', 'country');
insert into songs (Title, Artist, Genre) values ('Firefly Waltz', 'James Perez', 'metal');
